language: node_js
node_js:
- '4.2'
deploy:
  local_dir: build
  provider: s3
  on:
    branch: master
  skip_cleanup: true
  bucket: cruk.pebblecode.net
  region: eu-west-1
  access_key_id:
    secure: JWPAjYE6H5Zj4l3po7dFnBR9M+lvoYOYDC+B5adO+tZ1RlNV2e28kUH/YEsoGyXw7zj1CdgMupV4onJgu9uKlQ/i/WzYVJinlHp6mDAInFgUxdBrclBTNpJQ/b/xXyah7MQCdQnSuaOv4mjW+Go56LkCFUFCXjHKu6DQyh5Z6r+nMrUwBFsqjIWQu76elSHIuV9+tcxVxxhZCn0E0KHYDep7pAhFLwjFc4A6W6eav2lI3iItB6uhJU+UGzMvVIv5UhKvWGpbKYV6Ym7VcdHKp430Vom9dme2S23IKdfRce1DsWk8vFcbRF9/vwidENZVd2sNrCgRZ8R6hasOLU57RspEuYMxpICnvgfoEjCCGwE3F1PLEaT7fM/jWbs0x6+skZjOuFZgsI1iU9f73gENum/dBe99f795HMhg6dJ+/nCr/ONKpu3xWL076wB37VeKSfTqW4yvWr7WmhNzxbycaCxrmXlNcNOtVtcEBotRRp3VjvvdCe0QOTJDF1YMDptqYwrKtkjoJhWrM4o4//mEm1/kDZ2eJwuqLPEw6dHpSaEdRmc3pAtF52GDbL+Ki8Bta/4/7YwsAY8idK2DyEgngqNQgncYztqy5ZhSwChBtF8fRqrquwCX4JxGD4TmWtci/HzItmtsvAbUi8h2iT+adzTByMm/+YWFpOrKGzd7r1Y=
  secret_access_key:
    secure: YaikbvoszA3ULwkXQOHrRvaHdh+dCPOkgO+h7JbP+a/sbefsgIoNxVZ5PJsg3WrMZxkUimvKgeBCcxXRqJV+oJ866j5ypymntf8tvHsFqLq1LP51wpBdY7ZVuN/Gm/Aip5jIejZITp8wIqN6MR82viYFhF0VtTLf7zqFS94zllzrL7KdUu2zUFyzPi4cHF4xMdtFT4XAM167by76xZL8jKjowpOvBcrxhN2KLDDV5EWuU+5UCBumNYRCiLMUef6UT9j3CEEURosnaXNb1KxVadD2YANy1KqSpjrhu7Txbs21vxT+p53l9mdwppLZlnWXVGJ4kOyySXTqxGvkgw6Mg0FlQUUF5lhlrXeQpDXockrp69vl55Nt8iy/xfpCWHdzUpms3wVNAP4aFzDmz+LbquRHYQD8TkYcJe2jYc3VTwb+bOBDN6OrNiy5vgm5X6xZcv1NyZrbHOw9Sml4LkkoCQMp3fhx/ZqO+nKIhSSLMT+HKPTxb2l/XoOP1ut5gIwk5n2tb730FjLPMmkX/L3ItEnx+exQZSDgiYxbDj1ZAf8dt6CsikwkGPRWI5slYZU2L8wUH9f38KQqyIYn/KiNXPZWKaAydbPuEMHuoC2g5wpUju8QJcjromJsslmFPs4j848FO1g1jXCs/y77Kty03l6ApEsoiuyAd7zSGQ1ecEY=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- npm run build
