language: node_js
node_js:
- '4.2'
deploy:
  local_dir: build
  provider: s3
  on:
    branch: master
  skip_cleanup: true
  bucket: pebblecode-cruk
  script:
  - npm run build
  access_key_id:
    secure: A4fd9Nb4aHLrH3aa53AS2/33wnh74FimB711Yzt9heIFlQYsQuwvJI6T78Ad0VVDLPNFCLAv5bxvlGYq+0ULzdlbT+3alWd17LwrPioZf4bfsBBtLkow6ZuHDn8d65eGSYHh++3utoUrd2TMw2RppeqWx63LPgPoPyOHKxq/EGioRSP+mVILolKad5nmBa3KGnVKJtTaSqWJlVQd1hYYaMGBFy2/iYrdjriASOtrZpVNJLoJDFjeaFM/uHTI/rO4OcSCNcDdyLAOGqm81Buug4TKcRo3eaC+ySGX6stfeskZ2AmSLhyaLGaToIUT/MB3IevuZFz6Igx+WdtAOLXHax3zhMnh1vw9FKAAfip6ioupH+4CSa/s0YzJKWYL2CSrifpUwfVkw0V5kIDDxLLQbUyDvBIHKXXDBNSYJonyEMxcZlB0mJc0/Ul073d/fuSJXkjwCkPfwBeKc+/eLwbPlWMkhrUwA0H181kRQb4M9V2o1SHj7o2sflB1nsI2rcO/yVkZESejT2eHDGsdpzbWzuwOcO2Twui3YeCCwXUAegOQ5nIVoA8zA+C8QjwL3m/1gNx9VTchUX0JOyXBcZJb48sAS8ZUGJv5IXshzP+meSc3rF6Mbh8LdwXbs4rmw21zUxb5Mvy9KjTa2BDNJ8uuspeBVqjmigXuUKEjR7gPmC8=
  secret_access_key:
    secure: j8k5qz5C6n5h/UxFF2lr9UVG8iaC+9aYAzSOozDh11ntMqs6JX+yrNMo3kP4gPvaQ6yJqijBOiCqcifctoTlXcoo8lT8/MTHcTlzFN511FcWk6U/xbGd6vZ+eTPU9D43/C5eWxfLL7DBm1/kxK8G/nH/kpHnqNs+QqmVV557uU4MirUC3yMgFGEsUXojR87j2dwJ284+8OWDykYU0ueTjkl5hTwAAJT3YjvHerI/N86RICJgJWlLjor+f3psE7UhqWRrIUrEEW1a1BLLjSbFUnjwPzMflCBWiBNkm0efdstmJG1uepYJXFqH2qONcxBExu87lRUWe/kjxGS9N/gdd+d5zzarLbEjRw4CjJVJ9d3cA8RENeNzAqkQ6cRM9t4FCVGfV84K6A+9pAHG0JWZpYtoneIyluiHcKjXTZoboZibrDbOXbP/hFtiMugR/WNN5a0jUvCApGPqxXfxKRSpHZR0XJUfPuAelwbNn/29z/cZoS6ru4yWK0qcE/DPBFD5TSgBvhxPyYg+kj5HOpqb5ahNiPwpuZtyM8mhax2/s/ie/OmuzzXie1V3PVxpY/k21MosZi5LuMP/z75WJGNACOznc219Hs05Xw1nJ4YDUesbnlKjLiqmTGP2dTQh10KRoyX9QuAfI6ICGR+FjGyQM7v999v5ZGmSIBLM08ZHb6g=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
